name: gogreen_fleet
description: GoGreen Fleet - Vehicle Inventory Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  camera: ^0.11.2+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
